In [13]:
import numpy as np

In [14]:
# matrix with 3 row and 3 cols with pseudo casual values in [0...1]
matrix1 = np.random.randn(3, 3) 
print('matrix1',matrix1)

# matrix with 3 rows and 3 cols with pseudo casual values (int) in [1..8]
matrix2 = np.random.randint(1,8, size=(3, 3))
print('matrix2',matrix1)

# matrix with 3 row and 3 cols with pseudo casual values real numbers and sampled.
matrix3 = np.random.randn(3, 3) 
print('matrix3',matrix1)



matrix1 [[ 0.70145928 -0.14462917 -2.39233474]
 [ 0.73270472 -0.96965742 -0.04516919]
 [-0.77350296 -0.11897716  1.04608807]]
matrix2 [[ 0.70145928 -0.14462917 -2.39233474]
 [ 0.73270472 -0.96965742 -0.04516919]
 [-0.77350296 -0.11897716  1.04608807]]
matrix3 [[ 0.70145928 -0.14462917 -2.39233474]
 [ 0.73270472 -0.96965742 -0.04516919]
 [-0.77350296 -0.11897716  1.04608807]]


# to get pseudo casual   real values evenly distributed between a min include and max excluded

In [15]:
min = 10
max = 20
value = np.random.uniform(min,max)
print(value)    

16.885309375564212


In [16]:
# random choice of string with specify probability(80% and 20%)
print(np.random.choice(['head', 'cross'], size=5, p=[0.8, 0.2]))

['head' 'cross' 'head' 'head' 'head']


In [ ]:
# random choice of string with a value that has already been extracted will no longer be extracted
print(np.random.choice(['Qui', 'Quo', 'Qua'], size=5,replace=False))

In [19]:
# with seed instruction the output is the same when it will be performed 
np.random.seed(10)
print(np.random.rand(2,2))

[[0.77132064 0.02075195]
 [0.63364823 0.74880388]]
