In [1]:
from array import array

import numpy as np

In [13]:
ndarray = np.array([[[1, 2], [10, 20], [100, 200]]])
print(ndarray)
print('number of dimension', np.ndim(ndarray))
print('type of ndarray', type(ndarray))
print('elements for any size', np.shape(ndarray))
print('total elements', np.size(ndarray))

[[[  1   2]
  [ 10  20]
  [100 200]]]
number of dimension 3
type of ndarray <class 'numpy.ndarray'>
elements for any size (1, 3, 2)
total elements 6


In [4]:
# create a copy with a dimension of array
arr1 = ndarray.flatten()
print(arr1)

# maintains a reference with original array
arr2 = ndarray.ravel()
print(arr2)

arr1[0] = 0
arr2[1] = 0
print(arr1)
print(arr2)
print(ndarray)

[1 2 3 4 5 6]
[1 2 3 4 5 6]
[0 2 3 4 5 6]
[1 0 3 4 5 6]
[[1 0 3]
 [4 5 6]]


In [14]:
# You can modify the structure of ndarray (dimension) but the new dimension are compatible. For EX array with 12 elements 2 x 6 or 4 x 3 (matrix rows and cols)
arr1.shape = (3, 2)
print("Reshaped arr1:", arr1)

# Reshape the original ndarray to (2, -1) - will work since it has 6 elements
matr = ndarray.reshape(2, -1)
print("Reshaped ndarray:", matr)

Reshaped arr1: [[0 2]
 [3 4]
 [5 6]]
Reshaped ndarray: [[  1   2  10]
 [ 20 100 200]]


In [17]:
# if we make transpose matrix we use this instruction
arr3 = np.arange(24)
arr3 = arr3.reshape(4, 6)
print("Reshaped arr3:", arr3.T)

Reshaped arr3: [[ 0  6 12 18]
 [ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]]


In [19]:
# shift of elements 
# flatten and then shift
print('axis = None\n', np.roll(arr3,2)) 

# shift of whole rows
print('axis = 0\n', np.roll(arr3,1,axis=0))

# shift to the left in each rows
print('axis = 1 \n', np.roll(arr3,-1,axis=1))

axis = None
 [[22 23  0  1  2  3]
 [ 4  5  6  7  8  9]
 [10 11 12 13 14 15]
 [16 17 18 19 20 21]]
axis = 0
 [[18 19 20 21 22 23]
 [ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
axis = 1 
 [[ 1  2  3  4  5  0]
 [ 7  8  9 10 11  6]
 [13 14 15 16 17 12]
 [19 20 21 22 23 18]]
