In [35]:
import numpy as np
from mpmath import matrix

In [36]:
# array with elements from 0 to 11
arr = np.arange(12) 
print(arr)

# transform in a matrix 4 x 3
arr = arr.reshape(4,-1)
print('arr: \n',arr)

# return the list in python  corresponding to array
list = arr.tolist() 
print('list: \n',list)

# select the element of index 1 (all row)
print('arr[2]: ',arr[2]) 

# select the element of index 1 (all row) list 
print('list[2]: \n',list[2])




[ 0  1  2  3  4  5  6  7  8  9 10 11]
arr: 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
list: 
 [[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]]
arr[2]:  [6 7 8]
list[2]: 
 [6, 7, 8]


In [37]:
# slicing 
print('arr\n',arr)

# from 0 to penultimate element excluded
print('arr[:2]\n',arr[:2])

# from index 2 to 4 excluded
print('arr[2 : 4]\n',arr[2 : 4])

# from index 1 to 4 excluded with step two
print('arr[1:4:2]\n',arr[1:4:2])

# all row from 1 to 2 excluded 
print('arr[:, 1:2]\n',arr[:, 1:2])

# all elements of column of index 1
print('arr[:,1]\n',arr[:,1])

arr
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
arr[:2]
 [[0 1 2]
 [3 4 5]]
arr[2 : 4]
 [[ 6  7  8]
 [ 9 10 11]]
arr[1:4:2]
 [[ 3  4  5]
 [ 9 10 11]]
arr[:, 1:2]
 [[ 1]
 [ 4]
 [ 7]
 [10]]
arr[:,1]
 [ 1  4  7 10]


In [38]:
# array of index
print('arr\n',arr)

print(arr[[1,2,3]]) #rows
print(arr.flatten()[[1,2,3]]) # select the elements with this index now are values
print(arr[[1,2,3],0]) # select the elements [1,0] [2,0] [3,0]
print(arr[[1,2,3],[0,1,2]]) # elect the elements [1,0] [2,1] [3,2]

arr
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[1 2 3]
[3 6 9]
[ 3  7 11]


In [39]:
# array of boolean value 
# Create a boolean mask manually
print("Manual mask filter:\n", arr[[True, False, True, False]])

# Generate a random boolean filter for the array
filter = np.random.randint(0, 2, 4).astype(bool)
print('Random filter:\n', filter)

# Apply the filter to the array
print('Filtered array:\n', arr[filter])

# Boolean operations
print('arr > 5:\n', arr > 5)
print('arr[arr > 5]:\n', arr[arr > 5])
print('logical not:\n', arr[np.logical_not(arr <= 5)])
print('logical and:\n', arr[np.logical_and(arr > 15, arr < 35)])
print('logical or:\n', arr[np.logical_or(arr < 15, arr > 35)])
print('isin:\n', arr[np.isin(arr, [7, 4, 1, 8])])

# Working with slices and fancy indexing
ar = np.arange(10)
print('Original array:\n', ar)

# Slicing
slice_index = ar[0:2]  # [0,1,2]
print('Slice index:\n', slice_index)

# Fancy indexing with slice_index
fancy_index = ar[slice_index] # [0,1,2]
print('Fancy index:\n', fancy_index)

# Boolean indexing
bool_index = ar[np.logical_and(ar >= 0, ar <= 3)] # [0,1,2]
print('Boolean index:\n', bool_index)

# Modify slice_index, fancy_index, and bool_index without affecting original array `ar`
slice_index[0] = -1
# Ensure fancy_index has enough elements before changing values
if len(fancy_index) > 1:
    fancy_index[1] = -1 
# Ensure bool_index has enough elements before changing values
if len(bool_index) > 2:
    bool_index[2] = -1

print('Modified slice_index:\n', slice_index)
print('Modified fancy_index:\n', fancy_index)
print('Modified bool_index:\n', bool_index)
print('Original array after attempted modifications:\n', ar)

Manual mask filter:
 [[0 1 2]
 [6 7 8]]
Random filter:
 [ True False False  True]
Filtered array:
 [[ 0  1  2]
 [ 9 10 11]]
arr > 5:
 [[False False False]
 [False False False]
 [ True  True  True]
 [ True  True  True]]
arr[arr > 5]:
 [ 6  7  8  9 10 11]
logical not:
 [ 6  7  8  9 10 11]
logical and:
 []
logical or:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
isin:
 [1 4 7 8]
Original array:
 [0 1 2 3 4 5 6 7 8 9]
Slice index:
 [0 1]
Fancy index:
 [0 1]
Boolean index:
 [0 1 2 3]
Modified slice_index:
 [-1  1]
Modified fancy_index:
 [ 0 -1]
Modified bool_index:
 [ 0  1 -1  3]
Original array after attempted modifications:
 [-1  1  2  3  4  5  6  7  8  9]


In [41]:
# use of function arg_where 
# Create an array
ar1 = np.arange(6)
print('Original array:\n', ar)

# Use np.argwhere to find indices of elements that satisfy a condition
print('Indices where elements are even:\n', np.argwhere(ar % 2 == 0))

# Reshape the array into a 2x5 matrix
matrix = ar1.reshape(2, 3)
print('Original matrix:\n', matrix)

# Find indices of even elements in the reshaped matrix
print('Indices where elements in the matrix are even:\n', np.argwhere(matrix % 2 == 0))

Original array:
 [-1  1  2  3  4  5  6  7  8  9]
Indices where elements are even:
 [[2]
 [4]
 [6]
 [8]]
Original matrix:
 [[0 1 2]
 [3 4 5]]
Indices where elements in the matrix are even:
 [[0 0]
 [0 2]
 [1 1]]
